rm saved.txt
rm reward.txt
rm cumulative_reward.txt
rm loss.txt
rm bids.txt
rm reroute.txt
rm encounters.txt
rm flow.txt
rm gained.txt
rm gained_booster.txt
rm gained_off.txt
rm actions.txt
rm Q-values.txt
rm *.png
